language: ruby
services:
  - docker
rvm: 
  - 2.2.2

install:
  - bundle install
script:
  - docker-compose down
  - docker-compose up -d 
  - bundle exec rake set_settings_from_env
  - bundle exec rake set_pgpass
    # - bundle exec rake restore_schema
  - psql -h 127.0.0.1 -p 5433 -U twitter00 tlbk < createdb.dump
  - pg_dump -h 127.0.0.1 -p 5433 -U twitter00 tlbk
  - bundle exec rake test
