language: ruby
services:
  - docker
rvm: 
  - 2.2.2

install:
  - bundle install
script:
  - docker-compose down
  - docker-compose up -d 
  - bundle exec rake set_settings_from_env
  - bundle exec rake set_pgpass
  - bundle exec psql -U postgres < createdb.dump
  - pg_dumpall -U postgres 
  - bundle exec rake test
