language: ruby
services:
  - postgresql
rvm: 
  - 2.2.2

install:
  - bundle install
  - psql -c 'create database tlbk;' -U postgres
script:
  - bundle exec rake set_settings_from_env
  - bundle exec rake restore_schema
  - pg_dump -U postgres tlbk
  - bundle exec rake test
