language: ruby
services:
  - docker
rvm: 
  - 2.2.2

install:
  - bundle install
script:
  - docker-compose down
  - docker-compose up -d 
  - bundle exec rake set_settings_from_env
  - bundle exec rake set_pgpass
  - bundle exec rake restore_schema
  - pg_dump -U postgres tlbk
  - bundle exec rake test
