language: ruby
services:
  - docker
rvm: 
  - 2.2.2

install:
  - bundle install
script:
  - docker-compose down
  - docker-compose up -d 
  - bundle exec rake set_settings_from_env
  - bundle exec rake set_pgpass
  - psql -h 127.0.0.1 -U postgres -p 5433 < createdb.dump
  - pg_dump -U postgres -p 5433 tlbk
  - bundle exec rake test
