language: ruby
services:
  - docker
rvm: 
  - 2.2.2

install:
  - bundle install
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get -y remove --purge postgresql-9.1
  - sudo apt-get -y remove --purge postgresql-9.2
  - sudo apt-get -y remove --purge postgresql-9.3
  - sudo apt-get -y remove --purge postgresql-9.4
  - sudo apt-get -y autoremove
  - sudo apt-key adv --keyserver keys.gnupg.net --recv-keys 7FCC7D46ACCC4CF8
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.5" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get update
  - sudo apt-get -y install postgresql-9.5
  - sudo sh -c 'echo "local all postgres trust" > /etc/postgresql/9.5/main/pg_hba.conf'
  - sudo sh -c 'echo -n "host all all 127.0.0.1/32 trust" >> /etc/postgresql/9.5/main/pg_hba.conf'
  - sudo /etc/init.d/postgresql restart
  - psql --version
script:
  - docker-compose down
  - docker-compose up -d 
  - bundle exec rake set_settings_from_env
  - bundle exec rake set_pgpass
    # - bundle exec rake restore_schema
  - psql -h 127.0.0.1 -p 5433 -U twitter00 tlbk < createdb.dump
  - pg_dump -h 127.0.0.1 -p 5433 -U twitter00 tlbk
  - bundle exec rake test
